Add gRPC Dockerfile
drud/ddev-contrib pull request #104
Opened 2020-12-17 09:32 UTC by cmuench

Adds a small Dockerfile to enable gRPC in ddev projects.

2020-12-17 09:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/drud/ddev-contrib?pullRequest=104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/drud/ddev-contrib?pullRequest=104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/drud/ddev-contrib?pullRequest=104) it.</sub>

2020-12-17 15:14 UTC, rfay requested changes
Thanks for this! 
* Please add a little detail to the README saying why you'd want to use this.
* Please add an entry in the top-level README.md
Thanks!

2020-12-17 15:17 UTC, cmuench commented
@rfay ey ey, Sir. :-)

2020-12-18 14:59 UTC, rfay commented
Thanks so much! I'm on vacation but look forward to trying this out when I return after Christmas or in the new year.

2020-12-18 15:13 UTC, cmuench commented
@rfay ok. Have nice holidays.

2021-01-04 17:26 UTC, rfay approved these changes

2021-01-04 17:27 UTC, rfay commented on README.md
> +* [gRPC](web-web-container-dockerfiles/grpc)
```suggestion
* [gRPC](web-web-container-dockerfiles/grpc) (This is also a good example of adding a pecl module that is not supported via apt-get.)
```

2021-01-04 17:28 UTC, merged