Prepare "networks:" and "links:" for ddev v1.19
drud/ddev-contrib pull request #188
Opened 2022-01-11 13:01 UTC by jonaseberle

## The New Solution/Problem/Issue/Bug:
For ddev v1.19 we'll have to update services that need to be reachable or reach the router or inter-project services.

## How this PR Solves The Problem:
This removes superfluous `links:` and adds `networks: [ default, ddev ]` were inter-project communication is necessary.

## Related Issue Link(s):
https://github.com/drud/ddev/pull/3403

2022-01-11 15:02 UTC, rfay requested changes
Thanks for being so proactive about this! 

People are already having trouble with the documented [solr](https://github.com/drud/ddev/blob/master/pkg/servicetest/testdata/TestServices/docker-compose.solr.yaml), both people who are still on v1.18 and people who are trying out the v1.19.0-alpha1. We need to figure out a way to help people with both of those.

The people who are using solr for the first time hit the networks issue when using v1.18.2 because "ddev" doesn't exist. They can work around this with `docker network create ddev` but that will have to be mentioned somehow. Note that the docs point to the latest version of the docker-compose.solr.yaml, which doesn't actually work as-is with v1.18.2.

The people who already have solr and upgrade to v1.19.0-alpha1 have trouble because they're missing the networks stanza. But the trouble is quite mysterious - the ddev-router fails to come up because it can't find resolve the hostname. ddev-router gets notification of the new container coming up but can't resolve or contact it. 

I'll open a PR to try to help this on solr in a few minutes, will appreciate your thoughts and review. I did already add a caveat in the [release notes](https://github.com/drud/ddev/releases/tag/v1.19.0-alpha1), but it probably needs more work also.

2022-01-11 15:13 UTC, jonaseberle commented
This was not meant to be pulled before ddev 1.19 is out.

Oh, is https://github.com/drud/ddev/blob/master/pkg/servicetest/testdata/TestServices/docker-compose.solr.yaml linked somewhere in the docs? I think we could say this is not meant to be used before 1.19.

I also thought about how to make ddev projects "ready" for v1.19 without breaking v1.18 but have not come up with a good idea. 

I am back to work since today and I'll monitor discord/Slack now again and try to support. Also watching ddev issues/pulls.

2022-01-17 21:22 UTC, rfay requested changes
Needs to change from `networks: [default, ddev]` to `networks: [default, ddev_default]`

2022-01-18 08:54 UTC, jonaseberle commented
rebased and added `networks: [default, ddev_default]` to ALL services.

2022-01-18 14:37 UTC, rfay commented
It may still be a month or more before ready, but thanks for maintaining this! I still hope to get support for postgres into this release.

2022-02-27 17:12 UTC, rfay commented
We don't have to do this any more since ddev now adds the networks stanza, closing.

2022-02-27 17:12 UTC, closed without merging

2022-02-27 17:13 UTC, rfay commented
And thanks for *all* your work on this!