Add 'refresh' script for (re)initializing/resetting ddev environment
drud/ddev-contrib pull request #203
Opened 2022-02-20 18:45 UTC by hawkeyetwolf

2022-02-20 18:52 UTC, hawkeyetwolf commented on custom-commands/drupal-refresh/host/refresh
> +announce can_log_in          ddev login $verbose
This step relies on having the `login` script from this repo installed as well.

2022-02-20 18:54 UTC, hawkeyetwolf commented on custom-commands/drupal-refresh/host/refresh
> +announce can_build_composer  ddev task drupal:composer:development $verbose
These `ddev task` commands rely on [Drainpipe](https://github.com/Lullabot/drainpipe), but can be removed or replaced with your own steps. E.g., in this case:
```sh
ddev composer install --optimize-autoloader
```

2022-02-20 18:55 UTC, hawkeyetwolf commented on custom-commands/drupal-refresh/host/refresh
> +announce can_build_assets    ddev task assets $verbose
Can be replaced with, e.g.:
```sh
gulp
```

2022-02-20 18:57 UTC, hawkeyetwolf commented on custom-commands/drupal-refresh/host/refresh
> +announce can_update_drupal   ddev task drupal:update $verbose
Can be replaced with, e.g., a shell function to call the steps outlined in [this Lullabot ADR](https://architecture.lullabot.com/adr/20210924-drupal-build-steps).

2022-02-21 03:15 UTC, rfay requested changes
Thanks for this contribution!

* Please fill in the PR with information about what the PR is and what motivates it.
* The README.md should have your information at the bottom, like most of the other recipes.
* You need to add this to the top-level README.
* Since this is Drupal-specific, please edit the title to note that. 

I haven't looked the the specifics yet but very much appreciate the contribution. If you can get another user to manually test and review it it will help it get in faster.

2022-02-21 18:13 UTC, hawkeyetwolf commented
Thank you @rfay!! And apologies for not following the contribution guidelines... I was trying out this newfangled GitHub Codespaces thing, and it auto-created the PR for me. Will update the PR description later.

2022-02-21 18:28 UTC, rfay commented
All good, thanks!

2022-02-24 05:26 UTC, hawkeyetwolf commented
I decided to take out the dependency on [Drainpipe](https://github.com/Lullabot/drainpipe), so I need to do some more testing locally to make sure all the steps still work.

2022-03-16 20:42 UTC, rfay commented
Did you get this to where you wanted it? If so, please mark ready for review.

2022-07-19 23:41 UTC, rfay commented
No response from OP. Happy to reopen when you're ready to mark it ready for review.

2022-07-19 23:41 UTC, closed without merging