Change port in Host System
drud/ddev-contrib pull request #99
Opened 2020-10-23 07:14 UTC by davidjguru

Change port for the Host in order to avoid conflicts when xdebug is enabled. 
Now uses port 9001, mapping 9001:9000 for Portainer.

2020-10-23 15:53 UTC, rfay requested changes
If portainer is running http (I think it is) then you'd be a lot better using HTTP_EXPOSE (and `expose` instead of `ports`. 

Currently this could only run on a single project. 

Several other examples here use the environment variable HTTP_EXPOSE and HTTPS_EXPOSE to expose something that is then routed through the ddev-router, meaning you can run multiple projects with this at once.

2020-10-26 15:24 UTC, davidjguru commented
Hi @rfay,
I have made modifications on the file taking into account your notes. I have tried to deploy several projects in parallel and everything seems to go very well with this port mapping for Portainer, working as expected. 
Thanks a lot for your feedback. 
Greetings.

2020-10-26 15:51 UTC, rfay requested changes

2020-10-26 15:51 UTC, rfay commented on docker-compose-services/portainer/README.md
>    - '3434:9000'
It looks like you still need to change this bit.

2020-10-26 17:14 UTC, rfay approved these changes
Thanks so much for all your good work on this!

2020-10-26 17:15 UTC, merged